name: portfolio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 6.1.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.2.1
  firebase_core: ^2.21.0
  cloud_firestore: ^4.12.2
  fluttertoast: ^8.2.2
  emailjs: ^1.3.0
  hoverover: ^0.1.1
  flutterwebapp_reload_detector: ^0.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/images/
  uses-material-design: true

